import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist( {
  variable: "--font-geist-sans",
  subsets: [ "latin" ],
} );

const geistMono = Geist_Mono( {
  variable: "--font-geist-mono",
  subsets: [ "latin" ],
} );

export const metadata = {
  title: "CourseZone",
  description: "Generated by create next app",
};

export default function RootLayout ( { children } ) {
  return (
    <html lang="en">
      <body
        className="bg-gray-900 text-white overflow-x-hidden"
      >


        <nav className="w-full  flex justify-center  bg-transparent border-b border-gray-800  shadow-md shadow-gray-800">
          <ul className="flex gap-4 p-4">
            <li className="cursor-pointer border border-gray-500 px-8 py-2 rounded-lg"><Link href={ "/server" }>server</Link></li>
          </ul>
        </nav>
        { children }
      </body>
    </html>
  );
}
